name: weather
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_styled_toast: ^2.0.0
  flutter_svg: ^0.22.0
  http: ^0.13.4
  intl: ^0.17.0
  logging: ^1.0.2
  path_provider: ^2.0.8
  provider: ^6.0.2



  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/cities.json
    - assets/images/
